theme = "light"

[editor]
line-number = "relative"
mouse = false
true-color = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
separator = "|"
right = ["selections", "file-type","position", "file-encoding", "file-line-ending"]

[editor.indent-guides]
render = true
character = "|"

[editor.file-picker]
hidden = true

[keys.normal]
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}" # Print the current line's git blame information to the statusline.
