[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.autoSearchPaths = true
basedpyright.analysis.useLibraryCodeForTypes = true
basedpyright.analysis.diagnosticMode = 'openFilesOnly'
basedpyright.analysis.typeCheckingMode = "off"

[[language]]
name = "python"
roots = ["pyproject.toml", ".git", "setup.py"]
language-servers = [ "ruff", "ty", "basedpyright"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
